###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mariadb:
        image: 'mariadb:11.0'
        working_dir: /application
        volumes:
            # - './projeto:/application'
            - ./data/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=banco_tw
            - MYSQL_USER=harry
            - MYSQL_PASSWORD=root
        ports:
            - '8184:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './projeto:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8181:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - './projeto:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/cli/conf.d/99-overrides.ini'
